buffer pool backing
valkmit/llmq pull request #1
Opened 2024-10-28 18:55 UTC by davidiola

- `BufferPool` impl to allow for allocating a chain of smaller buffers for a single byte msg from `Mapping`
- `Mapping` updates:
  - ring buffer with X `slots` that contain the index of a particular slot's buffer chain head
  - allocate space in backing for buffer pool
  - `Mapping` enqueue/dequeue fn signatures are now `&mut`, `ArcSwap` contains `Mutex<Mapping>`

2024-10-28 20:02 UTC, valkmit requested changes

2024-10-28 20:02 UTC, valkmit commented on Cargo.toml
> +futures-util = { version = "^0.3.30", features = ["sink"] }
Why not pin this version to ensure reproducability?

2024-10-28 20:02 UTC, valkmit commented on src/queue/buffer_pool.rs
> +                if (*self.pool[idx].header).free {
We will need to use atomics to read/write to this value, as both producer/consumer will be reading/writing to this value

Ideally, a compare-and-set type operation instead of an atomic read of free followed by a write

2024-10-28 20:02 UTC, valkmit commented on src/broker/client.rs
> +    pub(super) tx_mapping: ArcSwap<Option<StdMutex<Mapping>>>,
I'm assuming the switch to using mutexes was due to some kind of constraint with Rust's borrow checker? We should strive to have a lockfree design in the enqueue and dequeue sections of the code (as well as within the broker).

This isn't as big of an issue in the code as it stands because it seems like logically there will never be any contention as to who is doing the locking, and this is just sugar around plaing nice with the borrow checker. However, mutexes still do have a cost, and we should be willing to write unsafe code to not have them when we're confident that our design choice is safe

2024-10-28 20:02 UTC, valkmit commented on src/queue/buffer_pool.rs
> +            if (*current.header).length != 0 {
Comments and check are valid, perhaps raises an issue of if we care if we overwrite data?

Generally when performing a memcpy anywhere for example, the memcpy function itself doesn't check to see if there's actually data or not - maybe semantically we just don't care as it's a given that caller doesn't care about anything in here?

Perhaps this would be better suited as an assert

2024-10-28 20:02 UTC, valkmit commented on src/queue/buffer_pool.rs
>                  (*current.header).free = true;
writing to free should be atomic.

Thinking about this more, we need to change the ordering in which we write this data. Right now, we mark it as free, and then load the next index to follow.

In a scenario where the consumer is freeing a chain, and the producer's next is near the same area, the producer could grab the buffer and write a 0 to next before the consumer gets a chance to read the old next value. This would result in a very slow memory leak

Ensuring that we atomically read/write next prior to read/writing free here will address that

2024-10-29 17:45 UTC, davidiola commented on Cargo.toml
> +futures-util = { version = "^0.3.30", features = ["sink"] }
0.3.30 was [yanked](https://crates.io/crates/futures-util/versions) so cargo couldn't find, updated to pin to 0.3.31

2024-10-29 18:39 UTC, davidiola commented on src/queue/buffer_pool.rs
> +                if (*self.pool[idx].header).free {
`free` is now an `AtomicBool`, and this code block now uses [compare_exchange](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicBool.html#method.compare_exchange)

2024-10-29 18:39 UTC, davidiola commented on src/broker/client.rs
> +    pub(super) tx_mapping: ArcSwap<Option<StdMutex<Mapping>>>,
understood, to accomodate that design choice i moved fwd with [UnsafeCell](https://doc.rust-lang.org/std/cell/struct.UnsafeCell.html), although had to write a wrapper (`SyncMapping`) around it to coerce the compiler into believing it is `Send` & `Sync`

2024-10-29 18:39 UTC, davidiola commented on src/queue/buffer_pool.rs
> +            if (*current.header).length != 0 {
updated to an assert

2024-10-29 18:39 UTC, davidiola commented on src/queue/buffer_pool.rs
>                  (*current.header).free = true;
good catch on that corner case, swapped to Atomic types & read `next` before storing `free`

2024-10-29 19:31 UTC, merged